name: Build CUDA wheel

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  wheel:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 1

    - name: Enable MSVC build environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install CUDA 12.4 tool-chain
      uses: Jimver/cuda-toolkit@v0.2.16
      with:
        cuda: '12.4.1'

    - name: Debug pyproject.toml and submodule
      shell: pwsh
      run: |
        cat pyproject.toml
        if (Test-Path vendor/llama.cpp/pyproject.toml) { cat vendor/llama.cpp/pyproject.toml }
        ls vendor/llama.cpp
        git -C vendor/llama.cpp log -1

    - name: Build wheel
      shell: pwsh
      run: ./build-wheel.ps1

    - uses: actions/upload-artifact@v4
      with:
        name: wheel
        path: dist/*.whl

    - name: (tag push) Publish release asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.whl