name: Build CUDA wheel

on:
  push: { branches: ["main"] }
  pull_request:
  workflow_dispatch:

jobs:
  wheel:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with: { submodules: 'true', fetch-depth: 0 }

      - name: Enable MSVC build environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        shell: pwsh
        run: ./build-wheel.ps1

      - uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/*.whl

      - name: (tag push) Publish release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
