name: Build-wheel

on:
  push:            { branches: [ "main" ] }
  pull_request:    {}
  workflow_dispatch:

jobs:
  wheel:
    runs-on: windows-2022   # Windows-latest is fine too

    steps:
    # ---- clone code + submodules in one go -------------------------------
    - uses: actions/checkout@v4
      with:
        # grab the sub-module straight away (recursive = vendor/llama.cpp/…)
        submodules: recursive
        fetch-depth: 0

    # ---- MSVC build tools -------------------------------------------------
    - name: Enable MSVC env
      uses: ilammy/msvc-dev-cmd@v1
      with: { arch: x64 }

    # ---- minimal CUDA toolkit (headers + nvcc) ---------------------------
    # 12.4.1 = latest GA build the action knows about
    - name: Install CUDA 12.4
      uses: Jimver/cuda-toolkit@v0.2.16
      with: { cuda: '12.4.1' }

    # ---- build the wheel --------------------------------------------------
    - name: Build wheel
      shell: pwsh
      run: |
        ./build-wheel.ps1

    # ---- publish ----------------------------------------------------------
    - uses: actions/upload-artifact@v4
      with:
        name: wheel
        path: dist/*.whl

    - name: Attach to tagged release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with: { files: dist/*.whl }
