name: Build-wheel

on:
  push:            { branches: ["main"] }
  pull_request:    {}
  workflow_dispatch:

jobs:
  wheel:
    runs-on: windows-2022          # free on public repos

    steps:
    # ── clone *only* the main repo (faster) ───────────────────────────────
    - uses: actions/checkout@v4
      with:
        submodules: false          # we’ll do it ourselves
        fetch-depth: 1

    # ── MSVC environment ──────────────────────────────────────────────────
    - uses: ilammy/msvc-dev-cmd@v1
      with: { arch: x64 }

    # ── CUDA headers + nvcc (no GPU required) ────────────────────────────
    - name: Install CUDA 12.4
      uses: Jimver/cuda-toolkit@v0.2.16
      with: { cuda: "12.4.1" }      # latest tag the action knows

    # ── build the wheel ──────────────────────────────────────────────────
    - name: Build wheel
      shell: pwsh
      run: ./build-wheel.ps1

    # ── upload artefact ──────────────────────────────────────────────────
    - uses: actions/upload-artifact@v4
      with: { name: wheel, path: dist/*.whl }

    # optional: attach wheel when you push a git **tag**
    - name: Attach to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with: { files: dist/*.whl }
